name: Apple Silicon - LLVM From Source

on:
  push:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        run: |
          git clone --depth 1 https://github.com/ninja-build/ninja.git
          pushd ninja
          ./configure.py --bootstrap
          popd
          echo "${GITHUB_WORKSPACE}/ninja" >> $GITHUB_PATH

      - name: Clone llvm-project
        run: |
          if [ ! -d "llvm-project" ]; then
            git clone --depth 1 --single-branch --branch release/21.x https://github.com/llvm/llvm-project
          fi

      - name: Restore LLVM Cache
        id: cache-llvm-restore
        uses: actions/cache/restore@v4
        with:
          path: llvm-project/llvm-build
          key: ${{ runner.os }}-llvm-${{ hashFiles('llvm-project/llvm/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-llvm-

      - name: Unbreak Python
        run: |
          find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
          sudo rm -rf /Library/Frameworks/Python.framework/
          brew install --force python3 && brew unlink python3 && brew link --overwrite python3

      - name: Build LLVM
        if: steps.cache-llvm-restore.outputs.cache-hit != 'true'
        run: |
          cd llvm-project
          mkdir -p llvm-build && cd llvm-build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_TARGETS_TO_BUILD="host;X86" \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_OPTIMIZED_TABLEGEN=ON \
            ../llvm
          ninja

      - name: Save LLVM Cache
        uses: actions/cache/save@v4
        if: steps.cache-llvm-restore.outputs.cache-hit != 'true'
        with:
          path: llvm-project/llvm-build
          key: ${{ steps.cache-llvm-restore.outputs.cache-primary-key }}

      - name: Set LLVM_DIR
        run: echo "LLVM_DIR=${GITHUB_WORKSPACE}/llvm-project/llvm-build" >> $GITHUB_ENV

      - name: Build Project
        run: |
          mkdir -p build && cd build
          cmake -G Ninja -DLLVM_INSTALL_DIR=${{ env.LLVM_DIR }} -DLLVM_ENABLE_ASSERTIONS=ON ../
          ninja

      - name: Run tests
        run: |
          cd build
          ${{ env.LLVM_DIR }}/bin/llvm-lit -va ./test/
