name: Apple x86

on:
  push:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15-intel
    strategy:
      matrix:
        type: [Debug, Release]
    steps:
      - uses: actions/checkout@v2
      - name: Unbreak Python in Github Actions
        # See:
        #   * https://github.com/actions/runner-images/issues/2322
        #   * https://github.com/libui-ng/libui-ng/commit/97d9601e74fadea1f8d1869c77acbe24be2886e2
        run: |
          find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
          sudo rm -rf /Library/Frameworks/Python.framework/
          brew install --force python3 && brew unlink python3 && brew unlink python3 && brew link --overwrite python3
      - name: Install Dependencies
        run: |
          brew update
          brew install llvm@21
          brew install lit
      - name: Build `llvm-pass-template`
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DLLVM_INSTALL_DIR="/usr/local/opt/llvm@21/" -DCMAKE_BUILD_TYPE=${{ matrix.type }} ../
          make -j2
      - name: Run tests for `llvm-pass-template`
        run: |
          cd $GITHUB_WORKSPACE/build
          lit -va ./test/
      - name: Create dummy C file
        run: echo 'int main() { return 0; }' > test.c
      - name: Test ouroboros.sh commands
        run: |
          chmod +x ./ouroboros.sh
          ./ouroboros.sh help
          ./ouroboros.sh config
          ./ouroboros.sh build
          ./ouroboros.sh emit-llvm test.c
          ./ouroboros.sh run test.ll
          ./ouroboros.sh pipeline
          ./ouroboros.sh pipeline -O1
          ./ouroboros.sh inject -O1 test.ll
          ./ouroboros.sh test
          ./ouroboros.sh clean
          ./ouroboros.sh rebuild
