name: Ubuntu x86

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler:
          - { compiler: GNU, CC: gcc, CXX: g++ }
          - { compiler: LLVM, CC: clang, CXX: clang++ }
        type: [Debug, Release]
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        env:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-21 main"
          sudo apt-get update
          sudo apt-get install -y llvm-21 llvm-21-dev llvm-21-tools clang-21
          sudo apt-get install python3-setuptools
          sudo pip3 install lit
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DLLVM_INSTALL_DIR="/usr/lib/llvm-21/" -DCMAKE_BUILD_TYPE=${{ matrix.type }} -DLLVM_ENABLE_ASSERTIONS=ON ../
          make -j2
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE/build
          lit -va ./test/
      - name: Create dummy C file
        run: echo 'int main() { return 0; }' > test.c
      - name: Test ouroboros.sh commands
        run: |
          chmod +x ./ouroboros.sh
          ./ouroboros.sh help
          ./ouroboros.sh config
          ./ouroboros.sh build
          ./ouroboros.sh emit-llvm test.c
          ./ouroboros.sh run test.ll
          ./ouroboros.sh pipeline
          ./ouroboros.sh pipeline -O1
          ./ouroboros.sh inject -O1 test.ll
          ./ouroboros.sh test
          ./ouroboros.sh clean
          ./ouroboros.sh rebuild
