name: Ubuntu x86

on:
  push:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler:
          - { compiler: GNU, CC: gcc, CXX: g++ }
          - { compiler: LLVM, CC: clang, CXX: clang++ }
        type: [Debug, Release]
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        env:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-21 main"
          sudo apt-get update
          sudo apt-get install -y llvm-21 llvm-21-dev llvm-21-tools clang-21
          sudo apt-get install python3-setuptools
          sudo pip3 install lit
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DLLVM_INSTALL_DIR="/usr/lib/llvm-21/" -DCMAKE_BUILD_TYPE=${{ matrix.type }} ../
          make -j2
      - name: Run example
        run: |
          cd $GITHUB_WORKSPACE
          /usr/lib/llvm-21/bin/opt \
            --load-pass-plugin build/lib/libTailRecursionElimination.so \
            --passes="tailrecelim" \
            -disable-output \
            ./test/SimpleTest.ll
      - name: Run a single test
        run: |
          cd $GITHUB_WORKSPACE/build
          lit -va ./test/SimpleTest.ll
